name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - 'CNAME'
      - 'asciart.nfo'
      - '.github/workflows/pages.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'web/**'
      - '.github/workflows/pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      # Run lint only on pull requests; skip during main deploys
      - name: Lint (ESLint)
        if: ${{ github.event_name == 'pull_request' }}
        run: npm run lint

      - name: Sync ASCII art into public
        run: |
          if [ -f ../asciart.nfo ]; then cp ../asciart.nfo ./public/asciart.nfo; fi

      - name: Restore Next.js build cache
        uses: actions/cache@v4
        with:
          path: web/.next/cache
          key: ${{ runner.os }}-next-cache-${{ hashFiles('web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-next-cache-

      - name: Build (Next.js export)
        run: npm run build -- --no-lint

      # E2E only on pull requests; cache Playwright browsers between runs
      - name: Cache Playwright Browsers
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('web/package-lock.json') }}
      - name: Install Playwright Browsers
        if: ${{ github.event_name == 'pull_request' }}
        run: npx playwright install --with-deps

      - name: Run E2E (Playwright)
        if: ${{ github.event_name == 'pull_request' }}
        run: npm run test:ci

      # LHCI is relatively heavy; run on PR only
      - name: Lighthouse CI (warn-only)
        if: ${{ github.event_name == 'pull_request' }}
        run: npm run lhci
        continue-on-error: true

      - name: Include CNAME and .nojekyll
        run: |
          cp ../CNAME ./out/CNAME 2>/dev/null || true
          touch ./out/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/out

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
